# Group Reports

Endpoints for getting injury, transaction, and status data.

<!-- include(transaction_all.apib) -->

<!-- include(wsfb_news_injury.apib) -->

<!-- include(leader_hitting_repeater.apib) -->

<!-- include(leader_pitching_repeater.apib) -->
