## Injuries [/fantasylookup/json/json/named.wsfb_news_injury.bam]
### Get Current Injuries [GET]

Retrieve all players which are currently injured.

+ Response 200 (application/json)

        {
            "wsfb_news_injury": {
                "copyRight": " Copyright 2017 MLB Advanced Media, L.P.  Use of any content on this page acknowledges agreement to the terms posted here http://gdx.mlb.com/components/copyright.txt  ",
                "queryResults": {
                    "created": "2017-12-13T17:59:39",
                    "totalSize": "28",
                    "row": [
                        {
                            "insert_ts": "11/19",
                            "injury_desc": "Recovering from Sept. 2017 right shoulder surgery",
                            "position": "P",
                            "name_first": "Alex",
                            "display_ts": "November 19, 2017 at 2:23 AM ET",
                            "due_back": "2019",
                            "team_name": "Angels",
                            "injury_update": "Underwent right shoulder surgery Sept. 12.",
                            "league_id": "103",
                            "player_id": "543542",
                            "injury_status": "Offseason",
                            "name_last": "Meyer",
                            "team_id": "108"
                        },
                        ...
                    ]
                }
            }
        }
