FORMAT: 1A
HOST: http://mlb.mlb.com

# MLB Data Endpoints

<!-- include(sections/intro.md) -->

<!-- include(sections/player/index.apib) -->

<!-- include(sections/stats/index.apib) -->

<!-- include(sections/reports/index.apib) -->
