FORMAT: 1A
HOST: http://mlb.mlb.com

<!-- include(readme.md) -->

<!-- include(sections/player/index.apib) -->

<!-- include(sections/stats/index.apib) -->

<!-- include(sections/team/index.apib) -->

<!-- include(sections/game/index.apib) -->

<!-- include(sections/reports/index.apib) -->
