# Group Player Details

Endpoints for getting general player data. This data typically includes important dates for the player (birth, pro debut), some basic attributes like throwing/batting arm, height, weight as well as country of birth and college/schools attended.

<!-- include(search_player_all.apib) -->

<!-- include(player_info.apib) -->

<!-- include(player_teams.apib) -->
