## Player Info [/named.player_info.bam?sport_code={sport_code}&player_id={player_id}]
### Player Info [GET]
+ Parameters
    + sport_code: 'mlb' (string, required) - Should be 'mlb' for all requests.
    + player_id: '493316' (string, required) - The ID of the player.
+ Response 200 (application/json)

        {
            "player_info": {
                "copyRight": " Copyright 2017 MLB Advanced Media, L.P.  Use of any content on this page acknowledges agreement to the terms posted here http://gdx.mlb.com/components/copyright.txt  ",
                "queryResults": {
                    "created": "2017-12-11T17:24:10",
                    "totalSize": "1",
                    "row": {
                        "birth_country": "Cuba",
                        "name_prefix": "",
                        "name_display_first_last": "Yoenis Cespedes",
                        "college": "",
                        "height_inches": "10",
                        "death_country": "",
                        "age": "32",
                        "name_display_first_last_html": "Yoenis Céspedes",
                        "gender": "M",
                        "height_feet": "5",
                        "pro_debut_date": "2012-03-28T00:00:00",
                        "death_date": "",
                        "primary_position": "7",
                        "birth_date": "1985-10-18T00:00:00",
                        "team_abbrev": "NYM",
                        "status": "Active",
                        "name_display_last_first_html": "Céspedes, Yoenis",
                        "throws": "R",
                        "death_city": "",
                        "primary_position_txt": "LF",
                        "high_school": "",
                        "name_display_roster_html": "Céspedes, Y",
                        "name_use": "Yoenis",
                        "player_id": "493316",
                        "status_date": "2017-10-02T00:00:00",
                        "primary_stat_type": "hitting",
                        "team_id": "121",
                        "active_sw": "Y",
                        "primary_sport_code": "mlb",
                        "birth_state": "",
                        "weight": "220",
                        "name_middle": "",
                        "name_display_roster": "Cespedes, Y",
                        "end_date": "",
                        "jersey_number": "52",
                        "death_state": "",
                        "name_first": "Yoenis",
                        "bats": "R",
                        "team_code": "nyn",
                        "birth_city": "Granma",
                        "name_nick": "La Potencia",
                        "status_code": "A",
                        "name_matrilineal": "Milanes",
                        "team_name": "New York Mets",
                        "name_display_last_first": "Cespedes, Yoenis",
                        "twitter_id": "@ynscspds",
                        "name_title": "",
                        "file_code": "nym",
                        "name_last": "Cespedes",
                        "start_date": "2016-11-30T00:00:00",
                        "name_full": "Cespedes, Yoenis"
                    }
                }
            }
        }
