## Player Search [/json/named.search_player_all.bam?sport_code='mlb'&active_sw={active_sw}&name_part={name_part}]
### Search For Player(s) [GET]

Search for active and historic/inactive players by name.

The `active_sw` parameter should be set depending on whether you want to search for active or inactive players. You *can* omit this parameter, though you will notice a slower response time as the search is done across all (active and inactive) players.

::: note
If you're using a single search term i.e. using 'cespedes' instead of 'yoenis cespedes', you'll need to append a '%25' character to your search term. Without it, the request will return 500. See example.
:::

+ Parameters
    + active_sw: 'Y' (string, optional) - Set to 'Y' to search active players, and 'N' to search inactive/historic players.
    + name_part: 'cespedes%25' (string, required) - The player name to search for.
+ Response 200 (application/json)

        {
            "search_player_all": {
                "copyRight": " Copyright 2017 MLB Advanced Media, L.P.  Use of any content on this page acknowledges agreement to the terms posted here http://gdx.mlb.com/components/copyright.txt  ",
                "queryResults": {
                    "created": "2017-12-11T15:11:55",
                    "totalSize": "1",
                    "row": {
                        "position": "LF",
                        "birth_country": "Cuba",
                        "weight": "220",
                        "birth_state": "",
                        "name_display_first_last": "Yoenis Cespedes",
                        "college": "",
                        "height_inches": "10",
                        "name_display_roster": "Cespedes, Y",
                        "sport_code": "mlb",
                        "bats": "R",
                        "name_first": "Yoenis",
                        "team_code": "nyn",
                        "birth_city": "Granma",
                        "height_feet": "5",
                        "pro_debut_date": "2012-03-28T00:00:00",
                        "team_full": "New York Mets",
                        "team_abbrev": "NYM",
                        "birth_date": "1985-10-18T00:00:00",
                        "throws": "R",
                        "league": "NL",
                        "name_display_last_first": "Cespedes, Yoenis",
                        "position_id": "7",
                        "high_school": "",
                        "name_use": "Yoenis",
                        "player_id": "493316",
                        "name_last": "Cespedes",
                        "team_id": "121",
                        "service_years": "",
                        "active_sw": "Y"
                    }
                }
            }
        }
