# Group Team Details

Endpoints for getting team data. This data typically encompasses stadium information, contact details, and other team specific information.

<!-- include(team_all_season.apib) -->
