## List Teams [/lookup/json/named.team_all_season.bam?sport_code='mlb'&all_star_sw={all_star_sw}&sort_order={sort_order}&season={season}]
### List Teams By Season [GET]

Retrieve a list of major league teams that were active during a given season.

:::note
If `all_star_sw` is set to `'Y'`, you will instead receive data on the all star teams for that season.
:::
:::note
You can sort using the `sort_order` paramater. Ex: Sort in ascending order by the name field using `sort_by='name_asc'`
:::
+ Parameters
    + all_star_sw: 'N' (string, optional) - Set to 'Y' for all star data, and 'N' for regular season.
    + sort_order (string, optional) - Field to sort results by.
    + season: '2017' (string, required) - The season for which you want the stats.

+ Response 200 (application/json)

        {
            "team_all_season": {
                "copyRight": " Copyright 2017 MLB Advanced Media, L.P.  Use of any content on this page acknowledges agreement to the terms posted here http://gdx.mlb.com/components/copyright.txt  ",
                "queryResults": {
                    "created": "2017-12-14T23:34:39",
                    "totalSize": "30",
                    "row": [
                        {
                            "phone_number": "(602) 462-6500",
                            "venue_name": "Chase Field",
                            "franchise_code": "ARI",
                            "all_star_sw": "N",
                            "sport_code": "mlb",
                            "address_city": "Phoenix",
                            "city": "Phoenix",
                            "name_display_full": "Arizona Diamondbacks",
                            "spring_league_abbrev": "CL",
                            "time_zone_alt": "America/Phoenix",
                            "sport_id": "1",
                            "venue_id": "15",
                            "mlb_org_id": "109",
                            ...
                        },
                        ...
                    ]
                }
            }
        }
