# Group Player Stats

Endpoints for getting player stats. This data typically encompasses pitching/batting stats per season, league, game type and also projected stats.

<!-- include(stats_team.apib) -->

<!-- include(stats_career.apib) -->

